Import('env', 'sys', 'os')
renderEnv = env.Clone()
renderEnv.Append(CPPDEFINES = [['MTS_BUILD_MODULE', 'MTS_MODULE_EMCA']] )

emca = [
	'stream.cpp',
	'sstream.cpp',
	'server.cpp',
	'userdata.cpp',
	'vertexdata.cpp',
	'pathdata.cpp',	
	'dataapi.cpp',
	'dataapimitsuba.cpp',
	'renderinfo.cpp',
	'camera.cpp',	
	'mesh.cpp',
	'meshes.cpp',
	'sphericalview.cpp',
	'toolhandler.cpp',
	'rendercontroller.cpp'
]

libemca = renderEnv.SharedLibrary('mitsuba-emca', emca)
env.Append(LIBS=['mitsuba-emca'])
env.Append(LIBPATH=[os.path.join(env['BUILDDIR'], 'libemca')])